version: '3'


services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    networks:
      - imersao-network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
#      - "host.docker.internal:host-gateway"

networks:
  imersao-network:
    name: imersao-network
#    driver: bridge
    external: true